apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pro
  template:
    metadata:
      labels:
        app: pro
    spec:
      containers:
      - name: pro
        image: racheldesta/pro:latest
        ports:
        - containerPort: 80
